# Site settings
title: Learn programming
header-img: img/home-bg.png
email: shktkt219@gmail.com
copyright_name: shktkt219
description: > # this means to ignore newlines until "baseurl:"
  my tracks
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  shktkt219
learn_profile: shktkt219
email_username: shktkt219@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
